services:
  # vault:
  #   image: vault:latest
  #   container_name: vault
  #   ports:
  #     - "6532:8200"
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: "root"
  #     VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:6532"
  #   cap_add:
  #     - IPC_LOCK
  #   command: "server -dev -dev-root-token-id=root"

  web-api: 
    image: "suksest/web-api-sample:${BUILD_TAG}"
    ports:
      - "80:3000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:



