on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: build and push docker image
    runs-on: ubuntu-22.04
    steps:
      - name: checkout scm
        uses: actions/checkout@v4
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            suksest/web-api-go:${{ github.run_number }}
            suksest/web-api-go:latest

  deploy:
    name: Deploy to server
    runs-on: ubuntu-22.04
    needs:
    - build-and-push
    steps:
      - name: checkout scm
        uses: actions/checkout@v4
      - name: copy docker-compose.yaml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          source: docker-compose.yaml
          target: deployment
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker compose --env-file ${{ secrets.ENV_FILE }} --file ${{ secrets.DEPLOYMENT_PATH }}/docker-compose.yaml up --detach