on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: build and push docker image
    runs-on: ubuntu-22.04
    steps:
      - name: checkout scm
        uses: actions/checkout@v4
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: suksest/web-api-go:${{ github.run_number }}

  deploy:
    name: Deploy to server
    runs-on: ubuntu-22.04
    needs:
    - build-and-push
    steps:
      - name: deploy
        # uses: Autom3/docker-deployment-action@3.0.1
        # with:
        #   remote_docker_host: ${{ format('{0}@{1}', secrets.SERVER_USERNAME, secrets.SERVER_HOST) }}
        #   remote_docker_port: 22
        #   ssh_private_key: ${{ secrets.SSH_PRIV_KEY }}
        #   ssh_public_key: ${{ secrets.SSH_PUB_KEY }}
        #   copy_stack_file: true
        #   deploy_path: ${{ secrets.DEPLOYMENT_PATH }}
        #   args: --env-file ${{ secrets.ENV_FILE }} up -d
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yaml
          up-flags: "--detach"
          compose-flags: "--env-file ${{ secrets.ENV_FILE }}"
