on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: build and push docker image
    runs-on: ubuntu-22.04
    steps:
      - name: checkout scm
        uses: actions/checkout@v4
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: suksest/web-api-go:${{ github.run_number }}

  deploy:
    name: Deploy to server
    runs-on: ubuntu-22.04
    needs:
    - build-and-push
    steps:
      - name: deploy
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yaml
          compose-flags: --env-file ${{ secrets.ENV_FILE }}
          up-flags: --detach
